services:
  web:
    build: web
    container_name: web
    restart: always
    networks:
      - reverse-proxy

  api:
    build: api
    container_name: api
    restart: always
    deploy:
      replicas: 2
    networks:
      - reverse-proxy

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    environment:
      - HOST=exec.felys.dev
    ports:
      - 443:443
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy