services:
  web:
    build:
      context: web
      args:
        NEXT_PUBLIC_API: https://exec.felys.dev/api
    container_name: felys-interface
    restart: always
    networks:
      - reverse-proxy


  api:
    build: api
    restart: always
    deploy:
      replicas: 2
    networks:
      - reverse-proxy

  nginx:
    build: nginx
    container_name: felys-nginx
    restart: always
    environment:
      - HOST=exec.felys.dev
    ports:
      - 443:443
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy
