services:
  web:
    build:
      context: web
      args:
        NEXT_PUBLIC_API: https://localhost/api
    image: felysneko/felys-web:latest
    container_name: felys-interface
    restart: always
    networks:
      - reverse-proxy


  api:
    build: api
    image: felysneko/felys-api:latest
    restart: always
    deploy:
      replicas: 2
    networks:
      - reverse-proxy

  nginx:
    build: nginx
    image: felysneko/felys-nginx:latest
    container_name: felys-nginx
    restart: always
    environment:
      - HOST=localhost
    ports:
      - 443:443
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy
