services:
  web:
    build:
      context: ../web
      args:
        NEXT_PUBLIC_API: https://exec.felys.dev/api
    image: felysneko/felys-web:latest
    networks:
      - reverse-proxy

  api:
    build: ../api
    image: felysneko/felys-api:latest
    networks:
      - reverse-proxy

  nginx:
    build: ../nginx
    image: felysneko/felys-nginx:latest
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy
