services:
  web:
    image: felysneko/felys-web:latest
    restart: always
    networks:
      - reverse-proxy

  api:
    image: felysneko/felys-api:latest
    restart: always
    deploy:
      replicas: 3
    networks:
      - reverse-proxy

  nginx:
    image: felysneko/felys-nginx:latest
    restart: always
    environment:
      - HOST=localhost
    ports:
      - 443:443
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: reverse-proxy
