[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
felys = "0.1.6"
tokio = { version = "1.38.1", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
tower-http = { version = "0.5.2", features = ["cors"] }
axum = "0.7.5"
